### ISSUE TITLE
docker compse is not picking up security information

### ISSUE THREAD

**Issue by samer1977** [kevdoran/flowops#2]
Hi ,

Im having a hard time making the yaml file work. I followed your template to setup a secure TLS nifi instance but I keep getting the nifi instance on default HTTP port 8080. not sure what Im doing wrong. Can you please help? Here is my yml file:

```
version: "3.5"
services:
    nifi:
        image: apache/nifi:latest
        container_name: nifi
        restart: unless-stopped
        network_mode: bridge
        ports:
            - "8443:8443"
        volumes:
            - /certs:/opt/certs
  
        environment:
            NIFI_WEB_HTTPS_HOST: '0.0.0.0'
            NIFI_WEB_HTTPS_PORT: 8443
            KEYSTORE_PATH: '/opt/certs/keystore.jks'
            KEYSTORE_PASSWORD: 'KEYSTOREPASSWORD'
            KEYSTORE_TYPE: JKS
            KEY_PASSWORD: 'KEYSTOREPASSWORD'
            TRUSTSTORE_PATH: '/opt/certs/truststore.jks'
            TRUSTSTORE_PASSWORD: 'TRUSTSTOREPASSWORD'
            TRUSTSTORE_TYPE: JKS
            INITIAL_ADMIN_IDENTITY: 'CN=my_user, OU=NiFi'
      
```
